name: Build

on:
  push:
    branches:
      - master  # Only run on push to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give script permission
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh
